#!/bin/bash

extensionPath="$(dirname "${0}")"
source "${extensionPath}/libs.sh"

number=50

help() {
  message="
Displays an interactive list of your starred repositories.
The URL of the selected repository is printed as the output of the command.

Dependencies: fzf, jq

Usage
  gh user-stars [NUMBER]

NUMBER: Number of stars to fetch at a time. (default: ${number}, max: 100)
"
  echo "${message}"
}

choose() {
  number=$1
  (loop_list_stars "${1}" & echo $! >&3) 3>"${extensionPath}/pid" | fzf --height 90% --layout=reverse
  kill $(<"${extensionPath}/pid") 2>/dev/null
}

while [ $# -gt 0 ]; do
  case "$1" in
  -h|--help)
    help
    exit 0
    ;;
  *)
    number=$1
  esac
  shift
done

if [[ $number -gt 100 ]]; then
  # detail: https://github.com/korosuke613/gh-user-stars/issues/8#issuecomment-910379829
  echo "Error: The maximum value of NUMBER is 100." >&2
  exit 1
fi

if ! type -p fzf >/dev/null; then
  echo "Error: Install \`fzf\` to use this command." >&2
  exit 1
fi

if ! type -p jq >/dev/null; then
  echo "Error: Install \`jq\` to use this command." >&2
  exit 1
fi

selected="$(choose "${number}")"
[ -n "$selected" ] || exit 1
echo "https://github.com/${selected%% *}"
