#!/bin/bash

extensionPath="$(dirname "${0}")"
source "${extensionPath}/libs.sh"

number=50

help() {
  message="
Displays an interactive your stars. The selected star is print url.
Dependencies: fzf

Usage
  gh user-stars [NUMBER]

NUMBER: Number of stars to fetch at a time. (default: ${number})
"
  echo "${message}"
}

choose() {
  number=$1
  (loop_list_stars "${1}" & echo $! >&3) 3>"${extensionPath}/pid" | fzf --height 90% --layout=reverse
  kill $(<"${extensionPath}/pid") 2>/dev/null
}

while [ $# -gt 0 ]; do
  case "$1" in
  -h|--help)
    help
    exit 0
    ;;
  *)
    number=$1
  esac
  shift
done

if ! type -p fzf >/dev/null; then
  echo "error: install \`fzf\` to use this command" >&2
  exit 1
fi

selected="$(choose "${number}")"
[ -n "$selected" ] || exit 1
echo "https://github.com/${selected%% *}"
